In [1]:
import numpy as np

In [2]:
# 0D Tensor

In [3]:
a=np.array(4)

In [4]:
print(a)

4


In [5]:
a # 0 D Tensor

array(4)

In [6]:
a.ndim # ndim = no of dimentional

0

In [7]:
# 1D Tensor | Vectors

In [8]:
arr=np.array([1,2,3,4]) 

In [9]:
print(arr)

[1 2 3 4]


In [10]:
arr # 1 D Tensor and 4D Vector

array([1, 2, 3, 4])

In [11]:
arr.ndim

1

In [12]:
# 2D Tensor | Matrices

In [13]:
# matrices is collection of the vectors

In [14]:
mat = np.array([[1,2,3],[2,3,4],[4,5,6]])

In [15]:
print(mat)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [16]:
mat

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [17]:
mat.ndim

2

In [22]:
!pip install jupyter_contrib_nbextensions

     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.3/23.5 MB ? eta -:--:--
     ---------------------------------------- 0.3/23.5 MB ? eta -:--:--
      -------------------------------------- 0.5/23.5 MB 541.0 kB/s eta 0:00:43
      -------------------------------------- 0.5/23.5 MB 541.0 kB/s eta 0:00:43
     - ------------------------------------- 0.8/23.5 MB 556.4 kB/s eta 0:00:41
     - ------------------------------------- 0.8/23.5 MB 556.4 kB/s eta 0:00:41
     - -------------------------

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Satish_Kundekar\\AppData\\Local\\Temp\\pip-unpack-6un7vhhw\\jupyter_contrib_nbextensions-0.7.0.tar.gz'
Consider using the `--user` option or check the permissions.



In [23]:
from sklearn.tree import DecisionTreeClassifier